
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-3
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBmv1pg","is_bot":false,"login":"livjono","name":"Olivia Jonokuchi"},"headRefName":"oj-HelpRequest-placeholder-copy","number":84,"title":"oj - remade HelpRequest Placeholders","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/84"},{"author":{"id":"MDQ6VXNlcjQ2NTM5Mzg4","is_bot":false,"login":"KarimBenyassine1","name":"Karim Benyassine"},"headRefName":"karim-ucsbdiningcommonsmenuitem-table","number":83,"title":"Created UCSBDiningCommonsMenuTable","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/83"},{"author":{"id":"U_kgDOBXgf8g","is_bot":false,"login":"wyatthspivak","name":""},"headRefName":"Wyatt-Articles-Table-Component","number":82,"title":"Created the Articles table and associated tests in the frontend","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/82"},{"author":{"id":"MDQ6VXNlcjQ2NTM5Mzg4","is_bot":false,"login":"KarimBenyassine1","name":"Karim Benyassine"},"headRefName":"karim-ucsbdiningcommonsmenuitem-form","number":78,"title":"Created the UCSB Dining Commons Menu Item Form","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/78"}]
