
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-3
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBqGjHg","is_bot":false,"login":"madisonlong1","name":""},"headRefName":"Madison-MenuItemReview","number":94,"title":"Madison, closes item 38","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/94"},{"author":{"id":"MDQ6VXNlcjQ2NTM5Mzg4","is_bot":false,"login":"KarimBenyassine1","name":"Karim Benyassine"},"headRefName":"karim-ucsbdiningcommonsmenuitem-edit","number":93,"title":"Created UCSB Dining Commons Menu Item Edit Page","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/93"},{"author":{"id":"MDQ6VXNlcjQ2NTM5Mzg4","is_bot":false,"login":"KarimBenyassine1","name":"Karim Benyassine"},"headRefName":"karim-ucsbdiningcommonsmenuitem-create","number":91,"title":"Added UCSB Dining Commons Menu Item Create Page","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/91"},{"author":{"id":"U_kgDOBX3Xdg","is_bot":false,"login":"kaitntom","name":""},"headRefName":"Kaitlyn-Org-form","number":90,"title":"Kaitlyn-Org-form and test done","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/90"},{"author":{"id":"U_kgDOBXgf8g","is_bot":false,"login":"wyatthspivak","name":""},"headRefName":"Wyatt-Copy-Placeholders-Articles-Page","number":89,"title":"Added placeholders for articles pages along with tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/89"}]
