
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-3
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBmv1pg","is_bot":false,"login":"livjono","name":"Olivia Jonokuchi"},"headRefName":"liv-HR-fixes","number":122,"title":"Liv - HelpRequest fixes for edit","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/122"},{"author":{"id":"MDQ6VXNlcjI2Mjg4OTA4","is_bot":false,"login":"kellyyan","name":"Kelly Yan"},"headRefName":"kelly-bug-fix","number":120,"title":"ky - fixed done field in recommendation request","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/120"}]
