
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-3
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ2NTM5Mzg4","is_bot":false,"login":"KarimBenyassine1","name":"Karim Benyassine"},"headRefName":"karim-ucsbdiningcommonsmenuitem-form","number":78,"title":"Created the UCSB Dining Commons Menu Item Form","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/78"},{"author":{"id":"MDQ6VXNlcjI2Mjg4OTA4","is_bot":false,"login":"kellyyan","name":"Kelly Yan"},"headRefName":"kelly-RecommendationRequest-backend","number":77,"title":"Created RestaurantRecommendations fixtures","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/77"},{"author":{"id":"MDQ6VXNlcjQ2NTM5Mzg4","is_bot":false,"login":"KarimBenyassine1","name":"Karim Benyassine"},"headRefName":"karim-ucsbdiningcommonsmenutiem-placeholders","number":73,"title":"Added placeholders for UCSB Dining Commons Menu Item ","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/73"}]
