
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-3
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBX3Xdg","is_bot":false,"login":"kaitntom","name":""},"headRefName":"Kaitlyn-Org-index","number":107,"title":"Kaitlyn org index done","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/107"},{"author":{"id":"U_kgDOBX3Xdg","is_bot":false,"login":"kaitntom","name":""},"headRefName":"Kaitlyn-Org-create","number":104,"title":"Kaitlyn org create","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/104"},{"author":{"id":"U_kgDOBmv1pg","is_bot":false,"login":"livjono","name":"Olivia Jonokuchi"},"headRefName":"oj-HelpRequest-index","number":102,"title":"oj - HelpRequest Index Page, plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/102"},{"author":{"id":"U_kgDOBqGjHg","is_bot":false,"login":"madisonlong1","name":""},"headRefName":"Madison-item40","number":100,"title":"MenuItemReview, item 40","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/100"}]
