
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-3
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-3
pull_requests: [{"author":{"id":"U_kgDOBXgf8g","is_bot":false,"login":"wyatthspivak","name":""},"headRefName":"Wyatt-Articles-backend","number":65,"title":"Copied over files for Backend CRUD API for Articles database table","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/65"},{"author":{"id":"U_kgDOBqGjHg","is_bot":false,"login":"madisonlong1","name":""},"headRefName":"Madison-MenuItemReview","number":64,"title":"ml-finished item 35","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/64"},{"author":{"id":"MDQ6VXNlcjI2Mjg4OTA4","is_bot":false,"login":"kellyyan","name":"Kelly Yan"},"headRefName":"kelly-RecommendationRequest-backend","number":63,"title":"ky - copied files for backend CRUD API RecommendationRequests","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/63"},{"author":{"id":"U_kgDOBmv1pg","is_bot":false,"login":"livjono","name":"Olivia Jonokuchi"},"headRefName":"liv-Readme","number":62,"title":"liv - Update readme links and title","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-3/pull/62"}]
